# Generated by Django 4.2.10 on 2024-04-02 10:50

import care_scribe.models.scribe
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facility", "0423_patientconsultation_consent_records_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScribeFile",
            fields=[
                (
                    "fileupload_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="facility.fileupload",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("facility.fileupload",),
        ),
        migrations.CreateModel(
            name="Scribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[care_scribe.models.scribe.validate_json_schema],
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("READY", "Ready"),
                            ("GENERATING_TRANSCRIPT", "Generating Transcript"),
                            ("GENERATING_AI_RESPONSE", "Generating Ai Response"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=50,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
