# Generated by Django 5.1.3 on 2025-01-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='json_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
