# Generated by Django 5.1.4 on 2025-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0002_scribe_json_prompt_scribe_system_prompt'),
        ('facility', '0476_facility_default_internal_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scribe',
            old_name='json_prompt',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='scribe',
            old_name='system_prompt',
            new_name='text',
        ),
        migrations.AddField(
            model_name='scribe',
            name='requested_in_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='scribe',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready'), ('GENERATING_TRANSCRIPT', 'Generating Transcript'), ('GENERATING_AI_RESPONSE', 'Generating Ai Response'), ('COMPLETED', 'Completed'), ('REFUSED', 'Refused'), ('FAILED', 'Failed')], default='CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='scribefile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Scribe Audio'), (2, 'Scribe Document')], default=1),
        ),
    ]
