# Generated by Django 5.1.4 on 2025-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0002_scribe_json_prompt_scribe_system_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scribe',
            old_name='json_prompt',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='scribe',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='scribe',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scribe',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready'), ('GENERATING_TRANSCRIPT', 'Generating Transcript'), ('GENERATING_AI_RESPONSE', 'Generating Ai Response'), ('COMPLETED', 'Completed'), ('REFUSED', 'Refused'), ('FAILED', 'Failed')], default='CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='scribefile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Scribe Audio'), (2, 'Scribe Document')], default=1),
        ),
    ]
