# Generated by Django 5.1.4 on 2025-02-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0002_scribe_json_prompt_scribe_system_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scribe',
            old_name='json_prompt',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='scribe',
            name='system_prompt',
        ),
    ]
