# Generated by Django 5.1.4 on 2025-05-03 17:35

import care_scribe.models.scribe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0003_rename_json_prompt_scribe_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[care_scribe.models.scribe.validate_json_schema_meta]),
        ),
    ]
