# Generated by Django 5.1.4 on 2025-05-13 09:11

import care_scribe.models.scribe
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0003_rename_json_prompt_scribe_prompt_and_more'),
        ('emr', '0028_alter_encounter_care_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[care_scribe.models.scribe.validate_json_schema_meta]),
        ),
        migrations.AddField(
            model_name='scribe',
            name='requested_in_encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.encounter'),
        ),
    ]
