# Generated by Django 5.1.4 on 2025-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0005_alter_scribe_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='audio_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='chat_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='chat_model_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
