# Generated by Django 5.1.4 on 2025-07-16 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0006_scribe_audio_model_scribe_chat_model_and_more'),
        ('facility', '0478_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scribefile',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='ScribeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('tokens', models.IntegerField(default=0, help_text='Total tokens available for the user/facility monthly')),
                ('allow_ocr', models.BooleanField(default=False, help_text='Whether the user/facility is allowed to use OCR features')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_scribe_quota', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scribe_quota', to='facility.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scribe_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scribe Quota',
                'verbose_name_plural': 'Scribe Quotas',
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
