# Generated by Django 5.1.4 on 2025-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0007_scribefile_meta_scribequota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scribequota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scribe',
            name='chat_input_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens used in the chat input', null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='chat_output_tokens',
            field=models.IntegerField(blank=True, help_text='Number of tokens used in the chat output', null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='feedback_comments',
            field=models.TextField(blank=True, help_text='Details of the feedback provided by the user', null=True),
        ),
        migrations.AddField(
            model_name='scribe',
            name='is_feedback_positive',
            field=models.BooleanField(blank=True, help_text='Whether the user has given positive feedback on the AI response', null=True),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='tnc_accepted_date',
            field=models.DateTimeField(blank=True, help_text='Date when the terms and conditions were accepted by the user', null=True),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='tnc_hash',
            field=models.CharField(blank=True, help_text='Hash of the terms and conditions accepted by the user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='tokens_per_user',
            field=models.IntegerField(default=0, help_text='Tokens available per user in the facility'),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='used',
            field=models.IntegerField(default=0, help_text='Tokens used by the user/facility in the current month'),
        ),
        migrations.AlterField(
            model_name='scribequota',
            name='tokens',
            field=models.IntegerField(default=0, help_text='Total tokens available for the facility monthly'),
        ),
    ]
