# Generated by Django 5.1.4 on 2025-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0007_scribequota'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribefile',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
