# Generated by Django 5.1.4 on 2025-08-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    def remove_scribe_flags(apps, schema_editor):
        flags_to_remove = ["SCRIBE_ADMIN", "SCRIBE_OCR_ENABLED", "SCRIBE_ENABLED"]

        UserFlag = apps.get_model('users', 'UserFlag')
        FacilityFlag = apps.get_model('facility', 'FacilityFlag')

        UserFlag.objects.filter(flag__in=flags_to_remove).delete()
        FacilityFlag.objects.filter(flag__in=flags_to_remove).delete()


    dependencies = [
        ('care_scribe', '0008_alter_scribequota_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_scribe_flags, migrations.RunPython.noop),
    ]
