# Generated by Django 5.1.4 on 2025-08-12 10:10

import care_scribe.care_scribe.models.scribe_question
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0009_remove_flags'),
        ('emr', '0031_rename_reason_for_visit_tokenbooking_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScribeQuestionnaireInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('instructions', models.JSONField(default=dict, validators=[care_scribe.care_scribe.models.scribe_question.validate_json_schema])),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scribe_questionnaires', to='emr.questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
