# Generated by Django 6.0 on 2025-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0009_remove_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribefile',
            name='file_category',
        ),
        migrations.AddField(
            model_name='scribefile',
            name='signed_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
