# Generated by Django 6.0 on 2025-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0010_remove_scribefile_file_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribefile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
